INSERT INTO `states` (`id`, `country_id`, `state_name`, `state_3_code`, `state_2_code`) VALUES
(1, '97', 'Andaman & Nicobar Islands', 'ANI', 'AI'),
(2, '97', 'Andhra Pradesh', 'AND', 'AN'),
(3, '97', 'Arunachal Pradesh', 'ARU', 'AR'),
(4, '97', 'Assam', 'ASS', 'AS'),
(5, '97', 'Bihar', 'BIH', 'BI'),
(6, '97', 'Chandigarh', 'CHA', 'CA'),
(7, '97', 'Chhatisgarh', 'CHH', 'CH'),
(8, '97', 'Dadra & Nagar Haveli', 'DAD', 'DD'),
(9, '97', 'Daman & Diu', 'DAM', 'DA'),
(10, '97', 'Delhi', 'DEL', 'DE'),
(11, '97', 'Goa', 'GOA', 'GO'),
(12, '97', 'Gujarat', 'GUJ', 'GU'),
(13, '97', 'Haryana', 'HAR', 'HA'),
(14, '97', 'Himachal Pradesh', 'HIM', 'HI'),
(15, '97', 'Jammu & Kashmir', 'JAM', 'JA'),
(16, '97', 'Jharkhand', 'JHA', 'JH'),
(17, '97', 'Karnataka', 'KAR', 'KA'),
(18, '97', 'Kerala', 'KER', 'KE'),
(19, '97', 'Lakshadweep', 'LAK', 'LA'),
(20, '97', 'Madhya Pradesh', 'MAD', 'MD'),
(21, '97', 'Maharashtra', 'MAH', 'MH'),
(22, '97', 'Manipur', 'MAN', 'MN'),
(23, '97', 'Meghalaya', 'MEG', 'ME'),
(24, '97', 'Mizoram', 'MIZ', 'MI'),
(25, '97', 'Nagaland', 'NAG', 'NA'),
(26, '97', 'Orissa', 'ORI', 'OR'),
(27, '97', 'Pondicherry', 'PON', 'PO'),
(28, '97', 'Punjab', 'PUN', 'PU'),
(29, '97', 'Rajasthan', 'RAJ', 'RA'),
(30, '97', 'Sikkim', 'SIK', 'SI'),
(31, '97', 'Tamil Nadu', 'TAM', 'TA'),
(32, '97', 'Telangana', 'TG', 'TS'),
(33, '97', 'Tripura', 'TRI', 'TR'),
(34, '97', 'Uttaranchal', 'UAR', 'UA'),
(35, '97', 'Uttar Pradesh', 'UTT', 'UT'),
(36, '97', 'West Bengal', 'WES', 'WE');
